token: imedia_rtsp_token
connect:
  iconfig: tcp://127.0.0.1:65400
subscribe:
  iconfig_pub: tcp://127.0.0.1:65401
  itrain_pub: tcp://127.0.0.1:65403
publish:
  imedia_rtsp_pub: tcp://127.0.0.1:65402
imedia_rtsp:
  image_setting_range: 255
